services:
  - type: web
    name: pothole-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app --timeout 120
    envVars:
      - key: MODEL_WARMUP
        value: "0"
    disk:
      name: pothole-data
      mountPath: /app/data
      sizeGB: 1