services:
  - type: web
    name: pothole-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MODEL_WARMUP
        value: "0"
      - key: PORT
        value: "5000"
    disk:
      name: pothole-data
      mountPath: /app/data
      sizeGB: 1